name: Deploy Vite App to EC2 Nginx Container

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci
    
    - name: Build Vite project
      run: npm run build
    
    - name: Compress dist folder
      run: tar -czf dist.tar.gz dist
    
    - name: Copy dist to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "dist.tar.gz"
        target: "~/"

    - name: SSH into EC2 and deploy to Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker ps
          docker exec nginxserver bash -c "rm -rf /usr/share/nginx/html/*"
          docker cp ~/dist.tar.gz nginxserver:/usr/share/nginx/html/
          docker exec nginxserver bash -c \
          "cd usr/share/nginx/html && tar -xzf dist.tar.gz\
           --strip-components=1 && rm dist.tar.gz"

